### ISSUE TITLE
Add Dev Container support for local development in VSCode

### ISSUE THREAD

**Issue by jurabek** [chayxana/Restaurant-App#67]
### Problem
Since this app supports multiple languages and frameworks, it is very hard to configure all those environments therefore we need to support setup development env more easily

### Solution
As the main solution becomes, VSCodes [dev container](https://code.visualstudio.com/docs/remote/containers) feature, which allows us to develop inside the docker containers.

#### System requirements 

- Windows: Docker Desktop 2.0+ on Windows 10 Pro/Enterprise. Windows 10 Home (2004+) requires Docker Desktop 2.3+ and the WSL 2 back-end. (Docker Toolbox is not supported. Windows container images are not supported.)
- macOS: Docker Desktop 2.0+.
- Linux: Docker CE/EE 18.06+ and Docker Compose 1.21+. (The Ubuntu snap package is not supported.)

**Comment by Jurabek** [comment]
### Problem
Since this app supports multiple languages and frameworks, it is very hard to configure all those environments therefore we need to support some development more easily

### Solution
As the main solution becomes, VSCodes [dev container](https://code.visualstudio.com/docs/remote/containers) feature, which allows us to develop inside the docker containers.

#### System requirements 

- Windows: Docker Desktop 2.0+ on Windows 10 Pro/Enterprise. Windows 10 Home (2004+) requires Docker Desktop 2.3+ and the WSL 2 back-end. (Docker Toolbox is not supported. Windows container images are not supported.)
- macOS: Docker Desktop 2.0+.
- Linux: Docker CE/EE 18.06+ and Docker Compose 1.21+. (The Ubuntu snap package is not supported.)

**Comment by jurabek** [comment]
At the moment vs code does not support multi-project dev in containers, [#1460](https://github.com/microsoft/vscode-remote-release/issues/1460)

**Comment by jurabek** [comment]
gitpod added as an alternative
- https://github.com/chayxana/Restaurant-App/pull/100
