### ISSUE TITLE
Too simple UI of the mobile app

### ISSUE THREAD

**Issue by coolbix** [chayxana/Restaurant-App#78]
The UI of the mobile app does not look alike the one in README.md.
It's too simple.
(I've built the latest app with Restaurant.Client.sln)

**Comment by jurabek** [comment]
@coolbix rollback to the older version in the git history, you will get look-alike on README.md.
At the moment a lot has been changed in the Xamarin architecture since we started developing, therefore, mobile part after upgrading Xamarin libs most of the parts had breaking changes, 
however, the main focus was writing clean and maintainable code not the UI part...

I hope it will help you, feel free to reopen if you have any other questions.
